services:
  minecraft:
    image: marctv/minecraft-papermc-server:latest
    restart: always
    container_name: "mcserver"
    environment:
      ENABLE_ROLLING_LOGS: "TRUE"
      MEMORYSIZE: "2G"
      TYPE: PAPER
      TZ: Azia/Tokyo
    volumes:
      - minecraftserver:/data
    ports:
      - "25565:25565"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
volumes:
  minecraftserver: